apiVersion: apps/v1
kind: Deployment
metadata:
  name: krew-installer
  labels:
    tags.datadoghq.com/env: "staging"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: "staging"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: replicated/node-pool
                operator: In
                values:
                - untrusted
      containers:
        - name: krew-installer
          image: 923411875752.dkr.ecr.us-east-1.amazonaws.com/krew-installer:latest
          imagePullPolicy: Always
          env:
            - name: USE_EC2_PARAMETERS
              value: "1"
            - name: GIT_SHA
              value: "GIT_SHA_PLACEHOLDER"
            - name: AWS_REGION
              value: us-east-1
            - name: LOG_LEVEL
              value: debug
            - name: USE_DATADOG_APM
              value: "true"
