steps:
  - label: build
    commands:
      - make deps build archive-modules
    artifact_paths:
      - "bin/*"
      - "build/**/*"
      - "node_modules.tar.gz"
    plugins:
      - docker#v3.2.0:
          image: replicated/gitops-builder:buildkite-go13-node10
          always-pull: true
          mount-checkout: true
          workdir: /go/src/github.com/replicatedhq/krew-installer
    retry:
      automatic:
        - exit_status: 2  #typically means yarn exited
          limit: 5

  - wait

  - label: build staging image
    commands:
      - mkdir -p bin
      - mkdir -p build
      - buildkite-agent artifact download bin/* bin/
      - buildkite-agent artifact download build/* build/
      - buildkite-agent artifact download node_modules.tar.gz .
      - tar xzf node_modules.tar.gz
      - rm node_modules.tar.gz
      - rm .dockerignore && cp deploy/.dockerignore .
      - ls
      - make build-staging
    branches: master
    env:
      AWS_PROFILE: replicated-staging
    plugins:
      - ecr#v2.0.0:
          login: true
          account_ids: "923411875752"

  - label: build production image
    commands:
      - mkdir -p bin
      - mkdir -p build
      - buildkite-agent artifact download bin/* bin/
      - buildkite-agent artifact download build/* build/
      - buildkite-agent artifact download node_modules.tar.gz .
      - tar xzf node_modules.tar.gz
      - rm node_modules.tar.gz
      - rm .dockerignore && cp deploy/.dockerignore .
      - ls
      - make build-production
    branches: master
    env:
      AWS_PROFILE: replicated-production
    plugins:
      - ecr#v2.0.0:
          login: true
          account_ids: "799720048698"

  - wait

  - commands:
      - make publish-staging
    branches: master
    retry:
      automatic:
        # this command exiting with status 2 typically means that the git commit collided with another
        - exit_status: 2
          limit: 5

  - block: "Release to production"
    branches: master

  - commands:
      - make publish-production
    branches: master
    retry:
      automatic:
        # this command exiting with status 2 typically means that the git commit collided with another
        - exit_status: 2
          limit: 5